version: 1

formatters:
  simple:
    format: '%(asctime) -15s %(funcName) -8s:%(module) -15s %(levelname) -8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: "[%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]
  propagate: no